FROM @gsd_baseimage@

ENV GEOSUPPORT_BASEDIR=@geosupport_basedir@
ENV GEOSUPPORT_BASEDIR="${GEOSUPPORT_BASEDIR:-/opt/geosupport}"
ENV GEOSUPPORT_HOME="${GEOSUPPORT_HOME:-${GEOSUPPORT_BASEDIR}/current}"
ENV GEOFILES="${GEOFILES:-${GEOSUPPORT_HOME}/fls/}"
ENV GS_LIBRARY_PATH="${GS_LIBRARY_PATH:-${GEOSUPPORT_HOME}/lib}"
ENV GS_INCLUDE_PATH="${GS_INCLUDE_PATH:-${GEOSUPPORT_HOME}/include}"

ARG GEOSUPPORT_RELEASE=@geosupport_release@
ARG GEOSUPPORT_MAJOR=@geosupport_major@
ARG GEOSUPPORT_MINOR=@geosupport_minor@
ARG GEOSUPPORT_PATCH=@geosupport_patch@

# version-@geosupport_major@@geosupport_release@@geosupport_patch@_@geosupport_major@.@geosupport_minor@
RUN mkdir -p "$GEOSUPPORT_BASEDIR"
WORKDIR $GEOSUPPORT_BASEDIR


VOLUME "${GEOSUPPORT_BASEDIR}" 
