#!/usr/bin/env bash

export GEOSUPPORT_HOME=@GEOSUPPORT_HOME@
export GEOFILES=$GEOSUPPORT_HOME/fls/
export GS_LIBRARY_PATH=$GEOSUPPORT_HOME/lib
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}${GS_LIBRARY_PATH}
export PATH=$PATH:$GEOSUPPORT_HOME/bin

function gslibinstall {
  # Will fail if not run as root
  echo $GS_LIBRARY_PATH > /etc/ld.so.conf.d/geosupport.conf
  ldconfig
}

function gsconf {
  echo GEOSUPPORT_HOME=$GEOSUPPORT_HOME
  echo GEOFILES=$GEOFILES
  echo GS_LIBRARY_PATH=$GS_LIBRARY_PATH
  echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
  echo PATH=$PATH
}
